import {
  type CountryCode,
  type CountryConfig,
  type CurrencyCode,
} from "./types";

export const currencyPerUsd: Record<CurrencyCode, number> = {
  INR: 83.12,
  USD: 1,
  GBP: 0.79,
  EUR: 0.92,
  AED: 3.67,
  SGD: 1.35,
  CAD: 1.36,
  AUD: 1.52,
};

export const cryptoRatesInUsd = {
  BTC: 68000,
  ETH: 3500,
  USDT: 1,
} as const;

export const formatMoney = (
  amountMinorUnits: number,
  currency: CurrencyCode,
  locale: string,
) =>
  new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    maximumFractionDigits: 2,
  }).format(amountMinorUnits / 100);

export const convertMinorUnits = (
  amountMinorUnits: number,
  fromCurrency: CurrencyCode,
  toCurrency: CurrencyCode,
) => {
  if (fromCurrency === toCurrency) {
    return amountMinorUnits;
  }

  const amountMajor = amountMinorUnits / 100;
  const usdValue = amountMajor / currencyPerUsd[fromCurrency];
  const convertedMajor = usdValue * currencyPerUsd[toCurrency];
  return Math.round(convertedMajor * 100);
};

export const countryConfigs: Record<CountryCode, CountryConfig> = {
  IN: {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    locale: "en-IN",
    taxSlabs: [
      { label: "0 - 3L", upToMinorUnits: 30000000, rate: 0 },
      { label: "3L - 7L", upToMinorUnits: 70000000, rate: 0.05 },
      { label: "7L - 10L", upToMinorUnits: 100000000, rate: 0.1 },
      { label: "10L - 12L", upToMinorUnits: 120000000, rate: 0.15 },
      { label: "12L - 15L", upToMinorUnits: 150000000, rate: 0.2 },
      { label: "15L+", upToMinorUnits: null, rate: 0.3 },
    ],
    taxFreeAllowanceMinorUnits: 5000000,
    payrollStrategy: "standard",
    socialSecurity: {
      pf: {
        label: "Provident Fund",
        employeeRate: 0.12,
        employerRate: 0.12,
        capMinorUnits: 1500000,
      },
      esi: {
        label: "ESI",
        employeeRate: 0.0075,
        employerRate: 0.0325,
        thresholdMinorUnits: 2100000,
      },
    },
    minimumWageAnnualMinorUnits: 24000000,
    maxHoursPerWeek: 48,
    overtimeMultiplier: 2,
    leavePolicy: {
      CL: { label: "Casual Leave", minimumDays: 12, carryForwardLimit: 0, paid: true, color: "#0ea5e9" },
      SL: { label: "Sick Leave", minimumDays: 12, carryForwardLimit: 6, paid: true, color: "#f97316" },
      PL: { label: "Privilege Leave", minimumDays: 18, carryForwardLimit: 10, paid: true, color: "#22c55e" },
      ML: { label: "Maternity Leave", minimumDays: 180, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PT: { label: "Paternity Leave", minimumDays: 10, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 60,
    probationDays: 180,
    dataPrivacyLaw: "DPDP Act 2023",
    publicHolidays: [
      { date: "2027-01-26", name: "Republic Day" },
      { date: "2027-03-08", name: "Holi" },
      { date: "2027-08-15", name: "Independence Day" },
      { date: "2027-10-31", name: "Diwali" },
      { date: "2027-12-25", name: "Christmas Day" },
    ],
    payFrequencies: ["Monthly", "Semi-Monthly"],
    mandatoryDeductions: [
      { label: "Professional Tax", calculation: "fixed", fixedEmployeeMinorUnits: 20000 },
      { label: "Labour Welfare Fund", calculation: "fixed", fixedEmployeeMinorUnits: 2000 },
    ],
    filingRequirements: ["PF filing", "ESI filing", "TDS filing", "Form 16 issuance"],
    contractorWithholdingRate: 0.1,
    cryptoPaySupported: true,
    workingDaysPerMonth: 22,
    marketSalaryBenchmarks: {
      "HR Business Partner": 240000000,
      "Payroll Specialist": 180000000,
      "People Operations Lead": 220000000,
      "Contract Recruiter": 120000000,
    },
  },
  US: {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    locale: "en-US",
    taxSlabs: [
      { label: "10%", upToMinorUnits: 1160000, rate: 0.1 },
      { label: "12%", upToMinorUnits: 4715000, rate: 0.12 },
      { label: "22%", upToMinorUnits: 10052500, rate: 0.22 },
      { label: "24%", upToMinorUnits: 19195000, rate: 0.24 },
      { label: "32%", upToMinorUnits: 24372500, rate: 0.32 },
      { label: "35%+", upToMinorUnits: null, rate: 0.35 },
    ],
    taxFreeAllowanceMinorUnits: 1460000,
    payrollStrategy: "standard",
    socialSecurity: {
      socialSecurity: {
        label: "Social Security",
        employeeRate: 0.062,
        employerRate: 0.062,
        capMinorUnits: 16860000,
      },
      medicare: {
        label: "Medicare",
        employeeRate: 0.0145,
        employerRate: 0.0145,
      },
    },
    minimumWageAnnualMinorUnits: 1508000,
    maxHoursPerWeek: 40,
    overtimeMultiplier: 1.5,
    leavePolicy: {
      PTO: { label: "Paid Time Off", minimumDays: 15, carryForwardLimit: 5, paid: true, color: "#22c55e" },
      SICK: { label: "Sick Leave", minimumDays: 8, carryForwardLimit: 4, paid: true, color: "#f97316" },
      MAT: { label: "Maternity Leave", minimumDays: 84, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Paternity Leave", minimumDays: 14, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 14,
    probationDays: 90,
    dataPrivacyLaw: "CCPA / state privacy laws",
    publicHolidays: [
      { date: "2027-01-01", name: "New Year's Day" },
      { date: "2027-05-31", name: "Memorial Day" },
      { date: "2027-07-04", name: "Independence Day" },
      { date: "2027-11-25", name: "Thanksgiving" },
      { date: "2027-12-25", name: "Christmas Day" },
    ],
    payFrequencies: ["Monthly", "Semi-Monthly", "Bi-Weekly", "Weekly"],
    mandatoryDeductions: [
      { label: "State Withholding", calculation: "rate", employeeRate: 0.05 },
      { label: "401(k) Auto Deferral", calculation: "rate", employeeRate: 0.03 },
    ],
    filingRequirements: ["W-2", "1099", "Federal withholding deposit", "State payroll filing"],
    contractorWithholdingRate: 0.1,
    cryptoPaySupported: true,
    workingDaysPerMonth: 21,
    marketSalaryBenchmarks: {
      "People Operations Manager": 13500000,
      "Payroll Manager": 12000000,
      "HR Generalist": 9500000,
      "HR Associate": 7000000,
    },
  },
  UK: {
    code: "UK",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    locale: "en-GB",
    taxSlabs: [
      { label: "Basic", upToMinorUnits: 5027000, rate: 0.2 },
      { label: "Higher", upToMinorUnits: 12514000, rate: 0.4 },
      { label: "Additional", upToMinorUnits: null, rate: 0.45 },
    ],
    taxFreeAllowanceMinorUnits: 1257000,
    payrollStrategy: "standard",
    socialSecurity: {
      ni: {
        label: "National Insurance",
        employeeRate: 0.08,
        employerRate: 0.138,
      },
      pension: {
        label: "Auto-Enrolment Pension",
        employeeRate: 0.05,
        employerRate: 0.03,
      },
    },
    minimumWageAnnualMinorUnits: 2288000,
    maxHoursPerWeek: 48,
    overtimeMultiplier: 1.5,
    leavePolicy: {
      AL: { label: "Annual Leave", minimumDays: 28, carryForwardLimit: 5, paid: true, color: "#22c55e" },
      SICK: { label: "Sick Leave", minimumDays: 10, carryForwardLimit: 5, paid: true, color: "#f97316" },
      MAT: { label: "Maternity Leave", minimumDays: 273, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Paternity Leave", minimumDays: 14, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 30,
    probationDays: 120,
    dataPrivacyLaw: "UK GDPR",
    publicHolidays: [
      { date: "2027-01-01", name: "New Year's Day" },
      { date: "2027-04-02", name: "Good Friday" },
      { date: "2027-04-05", name: "Easter Monday" },
      { date: "2027-05-31", name: "Spring Bank Holiday" },
      { date: "2027-12-27", name: "Christmas Observed" },
    ],
    payFrequencies: ["Monthly", "Weekly", "Bi-Weekly"],
    mandatoryDeductions: [
      { label: "Student Loan Deduction", calculation: "rate", employeeRate: 0.02 },
    ],
    filingRequirements: ["RTI filing", "P60 issuance", "P11D benefits reporting"],
    contractorWithholdingRate: 0.08,
    cryptoPaySupported: false,
    workingDaysPerMonth: 21,
    marketSalaryBenchmarks: {
      "HR Director": 9800000,
      "Compensation Manager": 8200000,
      "People Analyst": 6400000,
    },
  },
  DE: {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    locale: "de-DE",
    taxSlabs: [
      { label: "Entry", upToMinorUnits: 1500000, rate: 0.14 },
      { label: "Middle", upToMinorUnits: 6281000, rate: 0.24 },
      { label: "Upper", upToMinorUnits: 27782600, rate: 0.42 },
      { label: "Top", upToMinorUnits: null, rate: 0.45 },
    ],
    taxFreeAllowanceMinorUnits: 1160400,
    payrollStrategy: "standard",
    socialSecurity: {
      pension: {
        label: "Pension Insurance",
        employeeRate: 0.093,
        employerRate: 0.093,
      },
      health: {
        label: "Health Insurance",
        employeeRate: 0.0795,
        employerRate: 0.0795,
      },
      unemployment: {
        label: "Unemployment Insurance",
        employeeRate: 0.013,
        employerRate: 0.013,
      },
      nursing: {
        label: "Long-Term Care",
        employeeRate: 0.017,
        employerRate: 0.017,
      },
    },
    minimumWageAnnualMinorUnits: 2512200,
    maxHoursPerWeek: 48,
    overtimeMultiplier: 1.25,
    leavePolicy: {
      AL: { label: "Annual Leave", minimumDays: 20, carryForwardLimit: 5, paid: true, color: "#22c55e" },
      SICK: { label: "Sick Leave", minimumDays: 30, carryForwardLimit: 0, paid: true, color: "#f97316" },
      MAT: { label: "Maternity Leave", minimumDays: 98, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Parental Leave", minimumDays: 60, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 30,
    probationDays: 180,
    dataPrivacyLaw: "GDPR",
    publicHolidays: [
      { date: "2027-01-01", name: "Neujahr" },
      { date: "2027-04-02", name: "Karfreitag" },
      { date: "2027-04-05", name: "Ostermontag" },
      { date: "2027-10-03", name: "Tag der Deutschen Einheit" },
      { date: "2027-12-25", name: "Erster Weihnachtstag" },
    ],
    payFrequencies: ["Monthly"],
    mandatoryDeductions: [
      { label: "Solidarity Surcharge", calculation: "rate", employeeRate: 0.015 },
    ],
    filingRequirements: ["ELStAM filing", "Social insurance declaration", "Annual wage tax certificate"],
    contractorWithholdingRate: 0.08,
    cryptoPaySupported: false,
    workingDaysPerMonth: 21,
    marketSalaryBenchmarks: {
      "HR Operations Manager": 7600000,
      "People Partner": 7100000,
      "Compensation Analyst": 6900000,
    },
  },
  AE: {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "د.إ",
    locale: "en-AE",
    taxSlabs: [{ label: "No income tax", upToMinorUnits: null, rate: 0 }],
    taxFreeAllowanceMinorUnits: 0,
    payrollStrategy: "zero-tax",
    socialSecurity: {
      gpssa: {
        label: "GPSSA",
        employeeRate: 0.05,
        employerRate: 0.125,
      },
      gratuity: {
        label: "Gratuity Accrual",
        employeeRate: 0,
        employerRate: 0.0833,
      },
    },
    minimumWageAnnualMinorUnits: 3600000,
    maxHoursPerWeek: 48,
    overtimeMultiplier: 1.25,
    leavePolicy: {
      AL: { label: "Annual Leave", minimumDays: 30, carryForwardLimit: 10, paid: true, color: "#22c55e" },
      SICK: { label: "Sick Leave", minimumDays: 15, carryForwardLimit: 5, paid: true, color: "#f97316" },
      MAT: { label: "Maternity Leave", minimumDays: 60, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Paternity Leave", minimumDays: 5, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 30,
    probationDays: 180,
    dataPrivacyLaw: "UAE Personal Data Protection Law",
    publicHolidays: [
      { date: "2027-01-01", name: "New Year's Day" },
      { date: "2027-03-20", name: "Eid al-Fitr Holiday" },
      { date: "2027-06-27", name: "Arafat Day" },
      { date: "2027-12-02", name: "National Day" },
      { date: "2027-12-03", name: "National Day Holiday" },
    ],
    payFrequencies: ["Monthly"],
    mandatoryDeductions: [],
    filingRequirements: ["WPS submission", "End-of-service accrual reconciliation"],
    contractorWithholdingRate: 0,
    cryptoPaySupported: true,
    workingDaysPerMonth: 22,
    marketSalaryBenchmarks: {
      "Regional HR Lead": 42000000,
      "Payroll Manager": 30000000,
      "People Operations Specialist": 22000000,
    },
  },
  SG: {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    currency: "SGD",
    currencySymbol: "S$",
    locale: "en-SG",
    taxSlabs: [
      { label: "0 - 20k", upToMinorUnits: 2000000, rate: 0 },
      { label: "20k - 30k", upToMinorUnits: 3000000, rate: 0.02 },
      { label: "30k - 40k", upToMinorUnits: 4000000, rate: 0.035 },
      { label: "40k - 80k", upToMinorUnits: 8000000, rate: 0.07 },
      { label: "80k+", upToMinorUnits: null, rate: 0.11 },
    ],
    taxFreeAllowanceMinorUnits: 0,
    payrollStrategy: "standard",
    socialSecurity: {
      cpf: {
        label: "CPF",
        employeeRate: 0.2,
        employerRate: 0.17,
        capMinorUnits: 680000,
      },
    },
    minimumWageAnnualMinorUnits: 2640000,
    maxHoursPerWeek: 44,
    overtimeMultiplier: 1.5,
    leavePolicy: {
      AL: { label: "Annual Leave", minimumDays: 14, carryForwardLimit: 7, paid: true, color: "#22c55e" },
      SICK: { label: "Sick Leave", minimumDays: 14, carryForwardLimit: 7, paid: true, color: "#f97316" },
      MAT: { label: "Maternity Leave", minimumDays: 112, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Paternity Leave", minimumDays: 14, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 30,
    probationDays: 90,
    dataPrivacyLaw: "PDPA",
    publicHolidays: [
      { date: "2027-01-01", name: "New Year's Day" },
      { date: "2027-02-07", name: "Chinese New Year" },
      { date: "2027-05-01", name: "Labour Day" },
      { date: "2027-08-09", name: "National Day" },
      { date: "2027-12-25", name: "Christmas Day" },
    ],
    payFrequencies: ["Monthly"],
    mandatoryDeductions: [
      { label: "Skill Development Levy", calculation: "rate", employerRate: 0.0025 },
    ],
    filingRequirements: ["IR8A filing", "CPF submission", "Skills levy submission"],
    contractorWithholdingRate: 0.07,
    cryptoPaySupported: true,
    workingDaysPerMonth: 21,
    marketSalaryBenchmarks: {
      "Talent Acquisition Manager": 12800000,
      "People Operations Manager": 13500000,
      "HR Specialist": 8400000,
    },
  },
  CA: {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "C$",
    locale: "en-CA",
    taxSlabs: [
      { label: "Federal 15%", upToMinorUnits: 5586700, rate: 0.15 },
      { label: "Federal 20.5%", upToMinorUnits: 11173300, rate: 0.205 },
      { label: "Federal 26%", upToMinorUnits: 17320500, rate: 0.26 },
      { label: "Federal 29%", upToMinorUnits: 24675200, rate: 0.29 },
      { label: "Federal 33%", upToMinorUnits: null, rate: 0.33 },
    ],
    taxFreeAllowanceMinorUnits: 1570500,
    payrollStrategy: "standard",
    socialSecurity: {
      cpp: {
        label: "CPP",
        employeeRate: 0.0595,
        employerRate: 0.0595,
      },
      ei: {
        label: "EI",
        employeeRate: 0.0166,
        employerRate: 0.02324,
      },
    },
    minimumWageAnnualMinorUnits: 3328000,
    maxHoursPerWeek: 44,
    overtimeMultiplier: 1.5,
    leavePolicy: {
      AL: { label: "Vacation", minimumDays: 15, carryForwardLimit: 5, paid: true, color: "#22c55e" },
      SICK: { label: "Sick Leave", minimumDays: 10, carryForwardLimit: 5, paid: true, color: "#f97316" },
      MAT: { label: "Maternity Leave", minimumDays: 119, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Parental Leave", minimumDays: 35, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 14,
    probationDays: 90,
    dataPrivacyLaw: "PIPEDA",
    publicHolidays: [
      { date: "2027-01-01", name: "New Year's Day" },
      { date: "2027-07-01", name: "Canada Day" },
      { date: "2027-09-06", name: "Labour Day" },
      { date: "2027-10-11", name: "Thanksgiving" },
      { date: "2027-12-25", name: "Christmas Day" },
    ],
    payFrequencies: ["Monthly", "Bi-Weekly"],
    mandatoryDeductions: [{ label: "Provincial Tax", calculation: "rate", employeeRate: 0.05 }],
    filingRequirements: ["T4 issuance", "CPP filing", "EI filing"],
    contractorWithholdingRate: 0.08,
    cryptoPaySupported: true,
    workingDaysPerMonth: 21,
    marketSalaryBenchmarks: {
      "People Partner": 9800000,
      "Payroll Manager": 10800000,
      "HR Coordinator": 6800000,
    },
  },
  AU: {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: "A$",
    locale: "en-AU",
    taxSlabs: [
      { label: "0 - 18.2k", upToMinorUnits: 1820000, rate: 0 },
      { label: "18.2k - 45k", upToMinorUnits: 4500000, rate: 0.16 },
      { label: "45k - 135k", upToMinorUnits: 13500000, rate: 0.3 },
      { label: "135k - 190k", upToMinorUnits: 19000000, rate: 0.37 },
      { label: "190k+", upToMinorUnits: null, rate: 0.45 },
    ],
    taxFreeAllowanceMinorUnits: 0,
    payrollStrategy: "standard",
    socialSecurity: {
      superannuation: {
        label: "Superannuation",
        employeeRate: 0,
        employerRate: 0.115,
      },
      medicare: {
        label: "Medicare Levy",
        employeeRate: 0.02,
        employerRate: 0,
      },
    },
    minimumWageAnnualMinorUnits: 4799000,
    maxHoursPerWeek: 38,
    overtimeMultiplier: 1.5,
    leavePolicy: {
      AL: { label: "Annual Leave", minimumDays: 20, carryForwardLimit: 5, paid: true, color: "#22c55e" },
      SICK: { label: "Personal Leave", minimumDays: 10, carryForwardLimit: 5, paid: true, color: "#f97316" },
      MAT: { label: "Parental Leave", minimumDays: 126, carryForwardLimit: 0, paid: true, color: "#a855f7" },
      PAT: { label: "Partner Leave", minimumDays: 10, carryForwardLimit: 0, paid: true, color: "#6366f1" },
    },
    noticePeriod: 28,
    probationDays: 180,
    dataPrivacyLaw: "Privacy Act 1988",
    publicHolidays: [
      { date: "2027-01-01", name: "New Year's Day" },
      { date: "2027-01-26", name: "Australia Day" },
      { date: "2027-04-02", name: "Good Friday" },
      { date: "2027-12-25", name: "Christmas Day" },
      { date: "2027-12-26", name: "Boxing Day" },
    ],
    payFrequencies: ["Monthly", "Bi-Weekly", "Weekly"],
    mandatoryDeductions: [{ label: "Workers Insurance", calculation: "rate", employerRate: 0.01 }],
    filingRequirements: ["Single Touch Payroll", "PAYG withholding", "Super submission"],
    contractorWithholdingRate: 0.08,
    cryptoPaySupported: true,
    workingDaysPerMonth: 21,
    marketSalaryBenchmarks: {
      "People Operations Lead": 14500000,
      "Payroll Analyst": 9800000,
      "HR Advisor": 8800000,
    },
  },
};

export const supportedCountries = Object.keys(countryConfigs) as CountryCode[];
